import './globals.css';
import type { Metadata } from 'next';
import { Inter, Yuji_Syuku } from 'next/font/google';
import { DevGuidelines } from '@/components/dev/DevGuidelines';

const inter = Inter({ subsets: ['latin'] });
const yujiSyuku = Yuji_Syuku({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yuji-syuku'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${yujiSyuku.variable}`}>
        {children}
        <DevGuidelines />
      </body>
    </html>
  );
}
